name: Check RSS
on:
  schedule:
    - cron: '0 */2 * * *' # Tourne toutes les 2 heures

jobs:
  run-script:
    runs-runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip install feedparser requests
      - run: python script.py